//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Address_id { get; set; }
        public int User_id { get; set; }
        public string AddressName { get; set; }
        public string AddressDe { get; set; }
        public string Addressphone { get; set; }
        public System.DateTime AddressTime { get; set; }
        public int AddressCode { get; set; }
        public bool flat { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
