//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Forum()
        {
            this.Collection = new HashSet<Collection>();
            this.CommentForum = new HashSet<CommentForum>();
        }
    
        public int Forum_id { get; set; }
        public string ForumName { get; set; }
        public string ForumContent { get; set; }
        public System.DateTime ForumTime { get; set; }
        public int User_id { get; set; }
        public int ForumSection_id { get; set; }
        public string ForumImage { get; set; }
        public Nullable<int> ForumClicks { get; set; }
        public string ForumDec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection> Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentForum> CommentForum { get; set; }
        public virtual ForumSection ForumSection { get; set; }
        public virtual Users Users { get; set; }
    }
}
