//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.CommentGoods = new HashSet<CommentGoods>();
            this.Cart = new HashSet<Cart>();
            this.Order = new HashSet<Order>();
        }
    
        public int Goods_id { get; set; }
        public string GoodsName { get; set; }
        public string GoodsImage1 { get; set; }
        public string GoodsImage2 { get; set; }
        public string GoodsImage3 { get; set; }
        public Nullable<System.DateTime> Grounding { get; set; }
        public Nullable<System.DateTime> Undercarriage { get; set; }
        public Nullable<decimal> GoodsPrice { get; set; }
        public string GoodsDes { get; set; }
        public int Numbers { get; set; }
        public Nullable<int> Classify_id { get; set; }
        public string Company { get; set; }
    
        public virtual Classify Classify { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentGoods> CommentGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
