//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public History()
        {
            this.CommentHistory = new HashSet<CommentHistory>();
        }
    
        public int History_id { get; set; }
        public string HistoryTopic { get; set; }
        public string HistoryContent { get; set; }
        public string HistoryTime { get; set; }
        public int HistorySection_id { get; set; }
        public string HistoryPicture { get; set; }
        public Nullable<int> HistoryClassify_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentHistory> CommentHistory { get; set; }
        public virtual HistorySection HistorySection { get; set; }
    }
}
