//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryBook
    {
        public int Book_id { get; set; }
        public string Book_route { get; set; }
        public Nullable<System.DateTime> Upload_time { get; set; }
        public int Section_id { get; set; }
        public string Book_img { get; set; }
        public string Author { get; set; }
        public string Keyword { get; set; }
        public string PublishTime { get; set; }
        public Nullable<int> BookClassify_id { get; set; }
        public string AuthorCountry { get; set; }
        public string BookName { get; set; }
    
        public virtual HistorySection HistorySection { get; set; }
    }
}
