//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryVideo
    {
        public int Video_id { get; set; }
        public string Video_route { get; set; }
        public Nullable<System.DateTime> Video_date { get; set; }
        public string Keyword { get; set; }
        public string Video_img { get; set; }
        public int Section_id { get; set; }
        public int VideoClassify_id { get; set; }
        public string Actor { get; set; }
        public string Director { get; set; }
        public string VideoCountry { get; set; }
        public string VideoTime { get; set; }
        public string VideoName { get; set; }
    
        public virtual HistorySection HistorySection { get; set; }
    }
}
