//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilitaryVideo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MilitaryVideo()
        {
            this.CommendMilitaryVideo = new HashSet<CommendMilitaryVideo>();
        }
    
        public int MilitaryVideo_id { get; set; }
        public string MilitaryVideoName { get; set; }
        public string MilitaryVideoDecride { get; set; }
        public string MilitaryVideo_Ways { get; set; }
        public int ForumSection_id { get; set; }
        public System.DateTime MilitaryVideoTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommendMilitaryVideo> CommendMilitaryVideo { get; set; }
        public virtual ForumSection ForumSection { get; set; }
    }
}
