//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.CommentNews = new HashSet<CommentNews>();
        }
    
        public int News_id { get; set; }
        public System.DateTime SubmtDate { get; set; }
        public string Author { get; set; }
        public string NewsTitle { get; set; }
        public string NewsContent { get; set; }
        public int Section_id { get; set; }
        public string KeyWords { get; set; }
        public Nullable<int> Clicks { get; set; }
        public string NewsVideo { get; set; }
        public string NewsPicture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentNews> CommentNews { get; set; }
        public virtual NewSection NewSection { get; set; }
    }
}
