//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_id { get; set; }
        public int User_id { get; set; }
        public int Good_id { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
        public string Message { get; set; }
        public decimal TotalMoney { get; set; }
        public int Site_id { get; set; }
        public string State { get; set; }
        public System.DateTime OrderTime { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Users Users { get; set; }
    }
}
