//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedShare
    {
        public int RedShare_id { get; set; }
        public string RedShareName { get; set; }
        public string RedShareDes { get; set; }
        public System.DateTime RedShareTime { get; set; }
        public int RedSpots_id { get; set; }
        public string RedShareImage { get; set; }
        public int User_id { get; set; }
        public string RedShareD { get; set; }
    
        public virtual RedSpots RedSpots { get; set; }
        public virtual Users Users { get; set; }
    }
}
