//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplyHistory
    {
        public int ReplyHistory_id { get; set; }
        public Nullable<int> CommentHistory_id { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
        public string Content { get; set; }
        public Nullable<int> User_id { get; set; }
    
        public virtual CommentHistory CommentHistory { get; set; }
        public virtual Users Users { get; set; }
    }
}
