//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special
    {
        public int Special_id { get; set; }
        public int Manager_Id { get; set; }
        public string SpecialName { get; set; }
        public System.DateTime SpecialTime { get; set; }
        public string SpecialVideo { get; set; }
        public Nullable<int> SpecialClick { get; set; }
    
        public virtual Manager Manager { get; set; }
    }
}
